# NumPy

In [4]:
import numpy as np

In [9]:
arr=np.array([[1,2,3],[4,2,5]])

In [10]:
type(arr)

numpy.ndarray

In [12]:
print(arr.ndim) # print number of dimensions(axes)

2


In [13]:
print(arr.shape)

(2, 3)


In [14]:
print(arr.size)

6


In [15]:
print(arr.dtype)

int32


### Creation of NumPy Arrays

In [16]:
#Creating a numpy array from list
a=np.array([[1,2,3],[4,5,6]],dtype='float')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
#Creating a numpy array from tuple
b=np.array({1,3,2})
print(b)

{1, 2, 3}


In [23]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
d=np.ones((4,5))
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
e=np.full((3,3),6,dtype='complex')
print(e)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [28]:
f=np.random.random((4,5))
print(f)

[[0.06278743 0.61984149 0.18705904 0.27695735 0.94012442]
 [0.11698783 0.03840084 0.93544167 0.18967299 0.74921618]
 [0.68596563 0.22194346 0.65128358 0.59848326 0.17240545]
 [0.54825602 0.706441   0.68473769 0.43486723 0.16290499]]


In [27]:
g=np.eye(4)
print(g)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
h=np.arange(0,30,5)
print(h)

[ 0  5 10 15 20 25]


In [36]:
#np.arange?

In [31]:
i=np.linspace(0,5,10)
print(i)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [40]:
arr=np.array([[1,2,3],
              [4,2,5]])
newarr=arr.reshape((3,2))
print(newarr)

[[1 2]
 [3 4]
 [2 5]]


In [41]:
arr=np.array([[1,2,3],
              [4,2,5]])
newfltarr=arr.flatten()
print(newfltarr)

[1 2 3 4 2 5]


### Array Indexing

In [42]:
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])

In [43]:
arr[1:,:3]

array([[ 4. , -0.5,  6. ],
       [ 2.6,  0. ,  7. ],
       [ 3. , -7. ,  4. ]])

In [44]:
arr[1:,:3:2] # here '2' is the step size

array([[4. , 6. ],
       [2.6, 7. ],
       [3. , 4. ]])

In [45]:
cond=arr>0
temp=arr[cond]
print(temp)

[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


### Markdown

In [46]:
a=np.array([1,2,5,3])

In [50]:
a+1

array([2, 3, 6, 4])

In [51]:
a-3

array([-2, -1,  2,  0])

In [48]:
a*3

array([ 3,  6, 15,  9])

In [49]:
a**2

array([ 1,  4, 25,  9], dtype=int32)

In [54]:
#Transpose of an array
arr1=np.array([[1,2,3],
               [12,23,34],
               [13,12,11]])
newar=arr1.T
print(newar)

[[ 1 12 13]
 [ 2 23 12]
 [ 3 34 11]]


In [55]:
arr1.max()

34

In [56]:
arr1.max(axis=1)

array([ 3, 34, 13])

In [57]:
arr1.min(axis=0)

array([1, 2, 3])

In [58]:
arr1.sum()

111

In [59]:
arr1.cumsum(axis=1)

array([[ 1,  3,  6],
       [12, 35, 69],
       [13, 25, 36]], dtype=int32)

In [60]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[4,3],
           [2,1]])

In [61]:
a+b

array([[5, 5],
       [5, 5]])

In [62]:
a-b

array([[-3, -1],
       [ 1,  3]])

In [63]:
a*b

array([[4, 6],
       [6, 4]])

In [65]:
#Matrix multiplication
a.dot(b)

array([[ 8,  5],
       [20, 13]])

In [68]:
a=np.array([0,np.pi/2,np.pi])
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [69]:
a=np.array([1,2,3,4,])
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [70]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


### Sorting Array

In [71]:
arr1=np.array([[1,2,3],
               [12,23,34],
               [13,12,11]])

In [73]:
print(np.sort(arr1,axis=None,kind='mergesort'))

[ 1  2  3 11 12 12 13 23 34]


### Stacking and Splitting

In [74]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[4,3],
           [2,1]])

In [75]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [4 3]
 [2 1]]


In [76]:
print(np.hstack((a,b)))

[[1 2 4 3]
 [3 4 2 1]]


In [77]:
c=[5,6]
print(np.column_stack((a,c)))

[[1 2 5]
 [3 4 6]]


In [79]:
print(np.concatenate((a,b),1))

[[1 2 4 3]
 [3 4 2 1]]


In [80]:
a=np.array([[1,3,5,7,9,11],
           [2,4,6,8,10,12]])

In [81]:
print(np.hsplit(a,2))

[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [82]:
print(np.vsplit(a,2))

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


### Some more NumPy functions

In [83]:
a=np.array([[1,3,5,7,9,11],
           [2,4,6,8,10,12]])

In [84]:
print(np.mean(a))

6.5


In [85]:
print(np.std(a))

3.452052529534663


In [86]:
print(np.var(a))

11.916666666666666


### NumPy Random Module

In [88]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [89]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [90]:
b=np.random.randn(2,3)
print(b)

[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]


In [91]:
c=np.random.randint(5,10,3)
print(c)

[7 9 6]


In [93]:
element=np.random.choice([1,2,3,4,5,6,7])
print(element)

7
