# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Daksh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Daksh/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Daksh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Daksh/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Daksh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Daksh/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Daksh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Daksh/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [3]:
vect=np.zeros(10)
print(vect)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

First we calculate the size of the array by using the method .size and then calculate the size of single element of array using .itemsize. Then memory size is equal to (arr.size) * (arr.itemsize). For example, 

In [4]:
arr=np.array([12,45,23,47,84,52,78,23,46])
a=arr.size
b=arr.itemsize
c=a*b
print(a)
print(b)
print(c)

9
4
36


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [5]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
arr1=np.zeros(10)
arr1[4]=1
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr2=np.arange(10,49)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
print(arr2[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr3=np.linspace(0,8,9).reshape(3,3)
print(arr3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [15]:
arr4=np.array([1,2,0,0,4,0])
temp=np.transpose(np.nonzero(arr4))
print(temp)

[[0]
 [1]
 [4]]


#### 11. Create a 3x3 identity matrix

In [16]:
arr5=np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [18]:
arr6=np.random.random((3,3,3))
print(10*arr6)

[[[0.34969071 1.44708548 9.61495271]
  [6.51574209 9.95295317 8.65552078]
  [1.06128632 7.57672795 1.03330748]]

 [[8.4436913  2.36003878 1.10273812]
  [5.47359048 0.18144097 3.43643569]
  [4.59674446 3.7811479  1.46249846]]

 [[2.03176693 7.94273503 2.76984138]
  [3.850415   6.50871236 7.26289686]
  [2.02281713 1.40741831 8.20058396]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [21]:
arr7=np.random.random((10,10))
print(arr7)
print(arr7.min())
print(arr7.max())

[[0.58902965 0.30317686 0.25880718 0.86979457 0.09908722 0.89934791
  0.38018337 0.43049275 0.52109819 0.96495472]
 [0.92516113 0.44734544 0.21615836 0.55730963 0.1819173  0.85138622
  0.66469862 0.1983807  0.63079396 0.8752388 ]
 [0.68403402 0.58087295 0.78267928 0.55052829 0.0920182  0.57952567
  0.74116478 0.38871913 0.15090484 0.18538197]
 [0.13871773 0.05818499 0.20787396 0.96835905 0.38518264 0.36384205
  0.93867697 0.48657391 0.28550958 0.96662877]
 [0.44752205 0.4556789  0.48254018 0.20719893 0.16845822 0.46750162
  0.88021891 0.60574258 0.32628635 0.19304035]
 [0.42775966 0.87068021 0.48418732 0.73107252 0.84963213 0.5629548
  0.17217608 0.88929664 0.31336483 0.28339655]
 [0.59662835 0.40128056 0.12255702 0.08966182 0.52847844 0.67589495
  0.78342007 0.11450283 0.85184359 0.02039256]
 [0.89367991 0.0202334  0.6033558  0.19456246 0.77747994 0.98947374
  0.31015217 0.7688514  0.64938055 0.49343034]
 [0.40089755 0.52926333 0.37411995 0.03161565 0.5870084  0.72018722
  0.53648681 

#### 14. Create a random vector of size 30 and find the mean value

In [25]:
arr8=np.random.random(30)
print(arr8)
print(arr8.mean())

[0.20589589 0.98910457 0.47301367 0.30477377 0.01561221 0.45184208
 0.25913172 0.93951031 0.30251781 0.86513034 0.86931116 0.48185874
 0.57645182 0.45536576 0.59766974 0.31490359 0.94265548 0.3541852
 0.31824994 0.44598104 0.41454587 0.17737162 0.17098706 0.58868854
 0.71659338 0.66896976 0.43654458 0.44535765 0.53437389 0.29729393]
0.4871297042966533


#### 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
n=5
isl=np.zeros((n,n))
isl[0]=1
isl[n-1]=1
for i in range(n):
    isl[i][0]=1
    isl[i][n-1]=1
print(isl)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [35]:
n=5
test=np.random.random((n,n))
print(test)
test[0]=0
test[n-1]=0
for i in range(n):
    test[i][0]=0
    test[i][n-1]=0
print(test)

[[0.50658981 0.97946623 0.77205825 0.13323991 0.71758278]
 [0.96122712 0.35902041 0.85743744 0.21525761 0.91906196]
 [0.49655582 0.14951056 0.87838185 0.72823614 0.84750033]
 [0.19782547 0.46227477 0.78318111 0.86165848 0.67219889]
 [0.46510335 0.19421164 0.18836834 0.68485027 0.06185328]]
[[0.         0.         0.         0.         0.        ]
 [0.         0.35902041 0.85743744 0.21525761 0.        ]
 [0.         0.14951056 0.87838185 0.72823614 0.        ]
 [0.         0.46227477 0.78318111 0.86165848 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
arr9=np.zeros((5,5))
arr9[1][0]=1
arr9[2][1]=2
arr9[3][2]=3
arr9[4][3]=4
print(arr9)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [41]:
arr10 = np.zeros((8,8),dtype=int)
arr10[1::2,::2] = 1
arr10[::2,1::2] = 1
print(arr10)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [43]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)